version: '3.8'

services:
  pdf-processor:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./input:/app/input
      - ./output:/app/output
    network_mode: none
    container_name: pdf-processor